--- Execution Script
set serveroutput on

DECLARE 
  P_CUSTOMER_ID      NUMBER; 
  P_AMOUNT           NUMBER;
  P_AUTHORIZATION    NUMBER;
  P_STATUS_CODE      NUMBER;
  P_STATUS_MESSAGE   VARCHAR2(200);

BEGIN
  P_CUSTOMER_ID := '&customer';
  P_AMOUNT := '&amount';

billing.credit_request(
   P_CUSTOMER_ID => P_CUSTOMER_ID,
   P_AMOUNT => P_AMOUNT,
   P_AUTHORIZATION => P_AUTHORIZATION,
   P_STATUS_CODE => P_STATUS_CODE,
   P_STATUS_MESSAGE => P_STATUS_MESSAGE  ); 
commit;
DBMS_OUTPUT.PUT_LINE('P_CUSTOMER_ID = ' || P_CUSTOMER_ID); DBMS_OUTPUT.PUT_LINE('P_AMOUNT = ' || P_AMOUNT); 
DBMS_OUTPUT.PUT_LINE('P_AUTHORIZATION = ' || P_AUTHORIZATION); DBMS_OUTPUT.PUT_LINE('P_STATUS_CODE = ' || P_STATUS_CODE); DBMS_OUTPUT.PUT_LINE('P_STATUS_MESSAGE = ' || P_STATUS_MESSAGE);

END; 
/
